name: Docker Build & Push

on:
  push:
    branches: [ main ]
    paths: 
      - "src/**"
      - "pages/**"
      - "public/**"
      - "styles/**"
      - "Dockerfile"
      - "docker-compose.yaml"
      - "next.config.js"
      - "package.json"
      - "package-lock.json"
      - "!README.md"
      - ".env"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        required: false 
        description: 'Test scenario tags' 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ezzah/griffith-med:latest
            ezzah/griffith-med:${{ steps.vars.outputs.sha_short }}